#!/usr/bin/sh
#
# Thanks to Dragora for some help, for more information visit https://dragora.org/
#

export PATH="/usr/bin"

msg() { printf "live-init: %s\n" >> /dev/kmsg "$@"; }

rescue_shell() {
	msg "Error occurred! Dropping in rescue shell..."
	export PS1="[\e[0;31mRESCUE SHELL\e[m] $ "
	sulogin -p
	msg "Rebooting."
	sleep 1
	halt -r
}

dmesg -n 1
mkdir -p /dev /proc /sys /run /newroot

msg "Mounting pseudo-filesystems"
mount -t proc proc /proc -o nosuid,noexec,nodev || rescue_shell
mount -t sysfs sys /sys -o nosuid,noexec,nodev || rescue_shell
mount -t tmpfs run /run -o mode=0755,nosuid,nodev || rescue_shell
mount -t devtmpfs dev /dev -o mode=0755,nosuid || rescue_shell
mount -t tmpfs tmpfs -o rw,size=100% /newroot || rescue_shell
mkdir -p /run/lvm /dev/pts /dev/shm /newroot/cdrom /newroot/squash /newroot/rw /newroot/work /newroot/system || rescue_shell
mount -t devpts devpts /dev/pts -o mode=0620,gid=5,nosuid,noexec || rescue_shell
mount -t tmpfs shm /dev/shm -o mode=1777,nosuid,nodev || rescue_shell


live="0"

msg "Updating kernel modules"
depmod -a >/dev/null 2>&1

msg "Starting udev"
udevd --daemon || rescue_shell
udevadm trigger --action=add --type=subsystems || rescue_shell
udevadm trigger --action=add --type=devices || rescue_shell
udevadm trigger --action=change --type=devices || rescue_shell
udevadm settle || rescue_shell

msg "Mounting live media"
mount -n -r -t iso9660 -L ataraxialinux /newroot/cdrom || \
{
	sleep 3
	mount -n -r /dev/disk/by-label/ataraxialinux /newroot/cdrom || rescue_shell
}

mount -n -r -o loop -t squashfs /newroot/cdrom/seiba/seiba.sfs /newroot/squash || rescue_shell

msg "Merging live media"
mount -n -o lowerdir=/newroot/squash,upperdir=/newroot/rw,workdir=/newroot/work -t overlay overlay /newroot/system || rescue_shell

msg "Stopping udev"
udevadm control --exit

msg "Moving pseudo-filesystems"
mount --move /dev /newroot/system/dev || rescue_shell
mount --move /proc /newroot/system/proc || rescue_shell
mount --move /sys /newroot/system/sys || rescue_shell
mount --move /run /newroot/system/run || rescue_shell
mount --move /newroot/cdrom /newroot/system/media/cdrom || rescue_shell

msg "Switching root"
exec switch_root /newroot/system /usr/bin/init || rescue_shell
