#!/usr/bin/sh
#

umask 022
unalias -a

pushd() { command pushd "$1" > /dev/null; }
popd() { command popd "$1" > /dev/null; }
msg() { printf "\033[1;34m::\033[0m %s\n" "$@"; }
warn() { printf "\033[1;33m::\033[0m %s\n" "$@"; }
die() { printf "\033[1;31m::\033[0m %s\n" "$@"; exit 1; }

check_root() {
	if [[ $EUID -ne 0 ]]; then
		die "You must be root to run 'neko'"
	fi
}

copyfile() {
	[ -z "$1" ] && die "Specify file"

	while [ "$1" ]; do
		if [ ! -f "$rootdir/$1" ]; then
			die "$1: file not found"
		fi

		if [ ! -f "$tmpdir/$1" ]; then
			cp "$rootdir"/$1 "$tmpdir"/$1
		fi
		shift
	done
}

copylib() {
	[ -z "$1" ] && die "Specify file"

	while [ "$1" ]; do
		for i in $(ldd "$tmpdir"/$1 | awk '{print $3}' | sed -e 's|/lib|/usr/lib|' | sed -e 's|/usr/usr/lib|/usr/lib|'); do
			if [ ! -f "$rootdir/$i" ]; then
				warn "$i: file not found"
				break
			fi

			if [ ! -f "$tmpdir/$i" ]; then
				cp "$rootdir"/$i "$tmpdir"/$i
			fi
		done
		shift
	done
}

main() {
	export LC_ALL="POSIX"

	kernel="$(uname -r)"
	output="/boot/seiba.zst"

	while getopts k:o:r: opts; do
		case $opts in
			k) kernel="$OPTARG" ;;
			o) output="$OPTARG" ;;
			r) rootdir="$(realpath $OPTARG)"; rootdir="${rootdir%/}" ;;
		esac
	done
	shift $((OPTIND - 1))

	check_root

	tmpdir="$(mktemp -d)"

	cd "$tmpdir"
	mkdir -p dev usr/bin usr/lib/modules usr/lib/firmware run sys proc etc/udev/rules.d sysroot media
	mkdir -p usr/lib/systemd/system usr/lib/udev/rules.d usr/lib/modules-load.d usr/lib/sysctl.d
	mkdir -p usr/lib/systemd/system/sockets.target.wants usr/lib/systemd/system/sysinit.target.wants usr/lib/tmpfiles.d
	ln -sf usr/bin bin
	ln -sf usr/bin sbin
	ln -sf usr/lib lib
	ln -sf bin usr/sbin

	echo 'root:x:0:root' >> "$tmpdir"/etc/group
	echo 'systemd-journal:x:190:' >> "$tmpdir"/etc/group
	echo 'root:::root' >> "$tmpdir"/etc/gshadow
	echo 'systemd-journal:::' >> "$tmpdir"/etc/gshadow
	echo 'root:x:0:0:root:/:/usr/bin/mksh' >> "$tmpdir"/etc/passwd
	echo 'nobody:x:99:99:nobody:/:/usr/bin/nologin' >> "$tmpdir"/etc/passwd
	echo 'systemd-journal-gateway:x:191:191:systemd-journal-gateway:/:/usr/bin/nologin' >> "$tmpdir"/etc/passwd
	echo 'root::14871::::::' >> "$tmpdir"/etc/shadow
	echo 'nobody:x:14871::::::' >> "$tmpdir"/etc/shadow

	chmod 0600 "$tmpdir"/etc/gshadow "$tmpdir"/etc/shadow

	copyfile /usr/bin/mksh \
		/usr/bin/grep \
		/usr/bin/cat \
		/usr/bin/cp \
		/usr/bin/dd \
		/usr/bin/df \
		/usr/bin/killall \
		/usr/bin/ls \
		/usr/bin/mkdir \
		/usr/bin/mknod \
		/usr/bin/mount \
		/usr/bin/umount \
		/usr/bin/sed \
		/usr/bin/sleep \
		/usr/bin/ln \
		/usr/bin/rm \
		/usr/bin/uname \
		/usr/bin/kmod \
		/usr/bin/blkid \
		/usr/bin/chroot \
		/usr/bin/chown \
		/usr/bin/flock \
		/usr/bin/mv \
		/usr/bin/mkfifo \
		/usr/bin/setsid \
		/usr/bin/findmnt \
		/usr/bin/sulogin \
		/usr/bin/lvm \
		/usr/bin/dmsetup \
		/usr/bin/dmeventd \
		/usr/bin/less \
		/usr/bin/more \
		/usr/bin/swapon \
		/usr/bin/swapoff \
		/usr/bin/systemctl \
		/usr/bin/journalctl \
		/usr/bin/udevadm \
		/usr/bin/systemd-run \
		/usr/bin/systemd-escape \
		/usr/bin/systemd-cgls \
		/usr/bin/systemd-tmpfiles \
		/usr/bin/systemd-ask-password \
		/usr/bin/systemd-tty-ask-password-agent \
		/usr/lib/systemd/systemd \
		/usr/lib/systemd/systemd-cgroups-agent \
		/usr/lib/systemd/systemd-shutdown \
		/usr/lib/systemd/systemd-reply-password \
		/usr/lib/systemd/systemd-fsck \
		/usr/lib/systemd/systemd-udevd \
		/usr/lib/systemd/systemd-journald \
		/usr/lib/systemd/systemd-sysctl \
		/usr/lib/systemd/systemd-modules-load \
		/usr/lib/systemd/systemd-vconsole-setup \
		/usr/lib/systemd/systemd-volatile-root \
		/usr/lib/systemd/systemd-sulogin-shell \
		/usr/lib/systemd/system/cryptsetup.target \
		/usr/lib/systemd/system/emergency.target \
		/usr/lib/systemd/system/emergency.service \
		/usr/lib/systemd/system/sysinit.target \
		/usr/lib/systemd/system/basic.target \
		/usr/lib/systemd/system/halt.target \
		/usr/lib/systemd/system/kexec.target \
		/usr/lib/systemd/system/local-fs.target \
		/usr/lib/systemd/system/local-fs-pre.target \
		/usr/lib/systemd/system/remote-fs.target \
		/usr/lib/systemd/system/remote-fs-pre.target \
		/usr/lib/systemd/system/multi-user.target \
		/usr/lib/systemd/system/network.target \
		/usr/lib/systemd/system/network-pre.target \
		/usr/lib/systemd/system/network-online.target \
		/usr/lib/systemd/system/nss-lookup.target \
		/usr/lib/systemd/system/nss-user-lookup.target \
		/usr/lib/systemd/system/poweroff.target \
		/usr/lib/systemd/system/reboot.target \
		/usr/lib/systemd/system/rescue.target \
		/usr/lib/systemd/system/rescue.service \
		/usr/lib/systemd/system/rpcbind.target \
		/usr/lib/systemd/system/shutdown.target \
		/usr/lib/systemd/system/final.target \
		/usr/lib/systemd/system/sigpwr.target \
		/usr/lib/systemd/system/sockets.target \
		/usr/lib/systemd/system/swap.target \
		/usr/lib/systemd/system/timers.target \
		/usr/lib/systemd/system/paths.target \
		/usr/lib/systemd/system/umount.target \
		/usr/lib/systemd/system/sys-kernel-config.mount \
		/usr/lib/systemd/system/kmod-static-nodes.service \
		/usr/lib/systemd/system/systemd-tmpfiles-setup.service \
		/usr/lib/systemd/system/systemd-tmpfiles-setup-dev.service \
		/usr/lib/systemd/system/systemd-ask-password-console.path \
		/usr/lib/systemd/system/systemd-udevd-control.socket \
		/usr/lib/systemd/system/systemd-udevd-kernel.socket \
		/usr/lib/systemd/system/systemd-journald.socket \
		/usr/lib/systemd/system/systemd-journald-audit.socket \
		/usr/lib/systemd/system/systemd-ask-password-console.service \
		/usr/lib/systemd/system/systemd-modules-load.service \
		/usr/lib/systemd/system/systemd-halt.service \
		/usr/lib/systemd/system/systemd-poweroff.service \
		/usr/lib/systemd/system/systemd-reboot.service \
		/usr/lib/systemd/system/systemd-kexec.service \
		/usr/lib/systemd/system/systemd-fsck@.service \
		/usr/lib/systemd/system/systemd-udevd.service \
		/usr/lib/systemd/system/systemd-udev-trigger.service \
		/usr/lib/systemd/system/systemd-udev-settle.service \
		/usr/lib/systemd/system/systemd-journald.service \
		/usr/lib/systemd/system/systemd-vconsole-setup.service \
		/usr/lib/systemd/system/systemd-volatile-root.service \
		/usr/lib/systemd/system/systemd-random-seed.service \
		/usr/lib/systemd/system/systemd-sysctl.service \
		/usr/lib/systemd/system/ctrl-alt-del.target \
		/usr/lib/systemd/system/reboot.target \
		/usr/lib/systemd/system/systemd-reboot.service \
		/usr/lib/systemd/system/syslog.socket \
		/usr/lib/systemd/system/slices.target \
		/usr/lib/systemd/system/initrd.target \
		/usr/lib/systemd/system/initrd-fs.target \
		/usr/lib/systemd/system/initrd-root-device.target \
		/usr/lib/systemd/system/initrd-root-fs.target \
		/usr/lib/systemd/system/initrd-switch-root.target \
		/usr/lib/systemd/system/initrd-switch-root.service \
		/usr/lib/systemd/system/initrd-cleanup.service \
		/usr/lib/systemd/system/initrd-udevadm-cleanup-db.service \
		/usr/lib/systemd/system/initrd-parse-etc.service \
		/usr/lib/tmpfiles.d/systemd.conf \
		/usr/lib/sysctl.d/10-default.conf \
		/usr/lib/sysctl.d/50-default.conf \
		/usr/lib/udev/rules.d/10-dm.rules \
		/usr/lib/udev/rules.d/11-dm-lvm.rules \
		/usr/lib/udev/rules.d/13-dm-disk.rules \
		/usr/lib/udev/rules.d/50-udev-default.rules \
		/usr/lib/udev/rules.d/60-block.rules \
		/usr/lib/udev/rules.d/60-cdrom_id.rules \
		/usr/lib/udev/rules.d/60-persistent-storage.rules \
		/usr/lib/udev/rules.d/70-uaccess.rules \
		/usr/lib/udev/rules.d/71-seat.rules \
		/usr/lib/udev/rules.d/73-seat-late.rules \
		/usr/lib/udev/rules.d/75-net-description.rules \
		/usr/lib/udev/rules.d/80-drivers.rules \
		/usr/lib/udev/rules.d/80-net-setup-link.rules \
		/usr/lib/udev/rules.d/90-vconsole.rules \
		/usr/lib/udev/rules.d/95-dm-notify.rules \
		/usr/lib/udev/rules.d/99-systemd.rules \
		/usr/lib/udev/ata_id \
		/usr/lib/udev/cdrom_id \
		/usr/lib/udev/scsi_id
	copylib /usr/bin/mksh \
		/usr/bin/grep \
		/usr/bin/cat \
		/usr/bin/cp \
		/usr/bin/dd \
		/usr/bin/df \
		/usr/bin/killall \
		/usr/bin/ls \
		/usr/bin/mkdir \
		/usr/bin/mknod \
		/usr/bin/mount \
		/usr/bin/umount \
		/usr/bin/sed \
		/usr/bin/sleep \
		/usr/bin/ln \
		/usr/bin/rm \
		/usr/bin/uname \
		/usr/bin/kmod \
		/usr/bin/blkid \
		/usr/bin/chroot \
		/usr/bin/chown \
		/usr/bin/flock \
		/usr/bin/mv \
		/usr/bin/mkfifo \
		/usr/bin/setsid \
		/usr/bin/findmnt \
		/usr/bin/sulogin \
		/usr/bin/lvm \
		/usr/bin/dmsetup \
		/usr/bin/dmeventd \
		/usr/bin/less \
		/usr/bin/more \
		/usr/bin/swapon \
		/usr/bin/swapoff \
		/usr/bin/systemctl \
		/usr/bin/journalctl \
		/usr/bin/udevadm \
		/usr/bin/systemd-run \
		/usr/bin/systemd-escape \
		/usr/bin/systemd-cgls \
		/usr/bin/systemd-tmpfiles \
		/usr/bin/systemd-ask-password \
		/usr/bin/systemd-tty-ask-password-agent \
		/usr/lib/systemd/systemd \
		/usr/lib/systemd/systemd-cgroups-agent \
		/usr/lib/systemd/systemd-shutdown \
		/usr/lib/systemd/systemd-reply-password \
		/usr/lib/systemd/systemd-fsck \
		/usr/lib/systemd/systemd-udevd \
		/usr/lib/systemd/systemd-journald \
		/usr/lib/systemd/systemd-sysctl \
		/usr/lib/systemd/systemd-modules-load \
		/usr/lib/systemd/systemd-vconsole-setup \
		/usr/lib/systemd/systemd-volatile-root \
		/usr/lib/systemd/systemd-sulogin-shell

	ln -sf mksh "$tmpdir"/usr/bin/sh
	ln -sf /usr/lib/systemd/systemd "$tmpdir"/init

	for tool in {ins,ls,rm,dep}mod mod{probe,info}; do
		ln -sf kmod "$tmpdir"/usr/bin/$tool
	done
	for tool in lvchange lvrename lvextend lvcreate lvdisplay \
			lvscan pvchange pvck pvcreate pvdisplay pvscan \
			vgchange vgcreate vgscan vgrename vgck; do
		ln -sf lvm "$tmpdir"/usr/bin/$tool
	done

	for i in systemd-journald-audit.socket systemd-journald-dev-log.socket \
		systemd-journald.socket systemd-udevd-control.socket systemd-udevd-kernel.socket; do
		ln -sf /usr/lib/systemd/system/$i "$tmpdir"/usr/lib/systemd/system/sockets.target.wants/$i
	done
	for i in  kmod-static-nodes.service systemd-ask-password-console.path systemd-journald.service \
		systemd-modules-load.service systemd-sysctl.service systemd-tmpfiles-setup-dev.service \
		systemd-tmpfiles-setup.service systemd-udev-trigger.service systemd-udevd.service; do
		ln -sf /usr/lib/systemd/system/$i "$tmpdir"/usr/lib/systemd/system/sysinit.target.wants/$i
	done

	for i in emergency.target rescue.target systemd-ask-password-console.service; do
		systemctl -q --root "$tmpdir" add-wants "$i" systemd-vconsole-setup.service
	done

	for i in systemd-udevd.service systemd-udev-settle.service systemd-udev-trigger.service; do
		systemctl -q --root "$tmpdir" add-wants initrd.target "$i"
	done

	systemctl -q --root "$tmpdir" set-default initrd.target

	mkdir -p "$tmpdir"/var/lib/dbus
	ln -sf ../../../run/machine-id "$tmpdir"/var/lib/dbus/machine-id
	ln -sf ../run/machine-id "$tmpdir"/etc/machine-id

	touch "$tmpdir"/etc/initrd-release
	cat > "$tmpdir"/usr/lib/os-release <<- EOF
		NAME="The first anarchy server in Minecraft"
		VERSION="lel"
		ID="ataraxia"
		VERSION_ID="lel"
		PRETTY_NAME="The first anarchy server in Minecraft"
	EOF
}

main "$@"

exit 0

